### ISSUE TITLE
global name 'FileExistsError' is not defined

### ISSUE THREAD

**Issue by wisewtf** [Dapbler/cbr2cbz#17]
I've been testing out the script, but I haven't been able to get past this:

```python
[wise:plutus] 0
~/utilities/cbr2cbz: ./cbr2cbz.py /home/wise/source/work/ /opt/library/comics/Taskmaster/
Creating /tmp/cbr2cbztemp-u1000/p998406
Traceback (most recent call last):
  File "./cbr2cbz.py", line 803, in <module>
    main()
  File "./cbr2cbz.py", line 755, in main
    ,whatif=options.whatif
  File "./cbr2cbz.py", line 369, in cbr2cbz
    except FileExistsError:
NameError: global name 'FileExistsError' is not defined
```

Source directory contains one .cbr file called "'Taskmaster 005 (2021) (John_Williams).cbr" and destination folder exists and has correct permissions.

**Comment by mleduque** [comment]
You're probably running it with python2.
On debian/ubuntu (and anything like that), the "python" command will stay python2 by default (even whenit is removed, that's happening now in debian I think). i don't know what other distributions do.
This script is python3.

You either need to change the /usr/bin/python link or modify cbr2cbz.py to #!/usr/bin/python3

**Comment by PiDockMedia** [comment]
I was also confused for a short time on this. 

You could easily "fix" this by replacing the `#!/usr/bin/python` with `#!/usr/bin/env python3` at the top of the script. This allows it to find whichever your current default python3 is which is really important when you run in virtual python environments.

This method also follows the official recommendation:

https://www.python.org/dev/peps/pep-0394/#recommendation

I don't mind pulling this and suggesting the change.

**Comment by Dapbler** [comment]
Thanks for the pointer. I've changed the shebang to #!/usr/bin/env python3 and pushed to a new test branch - should add some tempdir autodetection/safety improvements to it also.

**Comment by Dapbler** [comment]
Promoted to the default branch.

**Comment by Dapbler** [comment]
Think it's time to close this one off - the change in #! has been in place for a few years.
I reinstalled my laptop the other day and will be trying to work out how I had git talking to github all those years ago.
